import React from 'react'

function Lowerbar() {
  return (
    <div className="Lowerbar">
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
        <p>LOWERBAR</p>
    </div>
  )
}

export default Lowerbar